site_name: ARCS
theme:
  logo: assets/ARCS_Logo.png
  name: material
  features:
    - navigation.instant  # Seamless page loads
    - navigation.tracking # Highlights TOC as you scroll
  palette:
    # Minimalist Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Minimalist Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter       # Clean, modern sans-serif
    code: JetBrains Mono
  
