from arcs.analysis import AnalyseSampling
import pytest
import numpy as np
from monty.serialization import loadfn


# GetEnergyandVibrationsVASP


def test_latex_equation():
    assert AnalyseSampling.latex_equation(
        "2H2 + O2 = 2H2O") == '<sub>2</sub>H<sub>2</sub> + O<sub>2</sub> = <sub>2</sub>H<sub>2</sub>O'
    # should add unusual compound like CH3_2CHCH2NH2


def test_sci_notation():
    assert AnalyseSampling.sci_notation(number=1e8) == '1.00 * 10^8'


def test_flip_reaction():
    reaction_data = {'equilibrium_constant': 5.277282624067824e-240,
                     'reaction': {'reaction_string': '2 H2O = 1 O2 + 2 H2',
                                  'reactants': {'H2O': 2},
                                  'products': {'O2': 1, 'H2': 2}}}

    assert AnalyseSampling.flip_reaction(reaction_data) == {'reaction': {'reactants': {'O2': 1, 'H2': 2},
                                                                         'products': {'H2O': 2},
                                                                         'reaction_string': '1 O2 + 2 H2 = 2 H2O'},
                                                            'equilibrium_constant': pytest.approx(1.894914620337658e+239)}


def test_reaction_statistics():
    outputdata = loadfn("./test_arcs_output.json")
    analysis = AnalyseSampling()
    stats = dict(analysis.reaction_statistics(outputdata))
    assert stats == {'2 H2O2 = 2 H2O + 1 O2': 2}


def test_average_sampling():
    outputdata = loadfn("./test_arcs_output.json")
    analysis = AnalyseSampling()
    avg = analysis.average_sampling(outputdata)
    print(avg)
    assert avg == {'initial': {'O3': 0.0,
                               'O2': 10.0,
                               'CH3COOH': 0.0,
                               'CH2O': 0.0,
                               'N2O2': 0.0,
                               'NO': 0.0,
                               'N2O4': 0.0,
                               'NO2': 0.0,
                               'HCOOH': 0.0,
                               'CH3CHO': 0.0,
                               'H2CO3': 0.0,
                               'N2': 0.0,
                               'NO3': 0.0,
                               'N2O': 0.0,
                               'CH4': 0.0,
                               'CH3OH': 0.0,
                               'CO2': 0.0,
                               'C2H5OH': 0.0,
                               'H2O': 10.0,
                               'C2H6O2': 0.0,
                               'CO': 0.0,
                               'C6H6': 0.0,
                               'HCN': 0.0,
                               'H2O2': 0.0,
                               'HNO2': 0.0,
                               'SO2': 0.0,
                               'SO3': 0.0,
                               'H2S': 0.0,
                               'H2SO4': 0.0,
                               'H2': 0.0,
                               'NH3': 0.0,
                               'C4H9NH2': 0.0,
                               'C3H7NH2': 0.0,
                               'COS': 0.0,
                               'S8': 0.0,
                               'HNO3': 0.0,
                               'CH3NH2': 0.0,
                               'H2SO3': 0.0,
                               'C2H5NH2': 0.0,
                               'NOHSO4': 0.0,
                               'CS2': 0.0,
                               'CH3_C6H5': 0.0,
                               'CH3_CO_CH3': 0.0},
                   'mean': {'O3': 0.0,
                            'O2': 9.999982691370992,
                            'CH3COOH': 0.0,
                            'CH2O': 0.0,
                            'N2O2': 0.0,
                            'NO': 0.0,
                            'N2O4': 0.0,
                            'NO2': 0.0,
                            'HCOOH': 0.0,
                            'CH3CHO': 0.0,
                            'H2CO3': 0.0,
                            'N2': 0.0,
                            'NO3': 0.0,
                            'N2O': 0.0,
                            'CH4': 0.0,
                            'CH3OH': 0.0,
                            'CO2': 0.0,
                            'C2H5OH': 0.0,
                            'H2O': 9.999965382741983,
                            'C2H6O2': 0.0,
                            'CO': 0.0,
                            'C6H6': 0.0,
                            'HCN': 0.0,
                            'H2O2': 3.46172580165353e-05,
                            'HNO2': 0.0,
                            'SO2': 0.0,
                            'SO3': 0.0,
                            'H2S': 0.0,
                            'H2SO4': 0.0,
                            'H2': 0.0,
                            'NH3': 0.0,
                            'C4H9NH2': 0.0,
                            'C3H7NH2': 0.0,
                            'COS': 0.0,
                            'S8': 0.0,
                            'HNO3': 0.0,
                            'CH3NH2': 0.0,
                            'H2SO3': 0.0,
                            'C2H5NH2': 0.0,
                            'NOHSO4': 0.0,
                            'CS2': 0.0,
                            'CH3_C6H5': 0.0,
                            'CH3_CO_CH3': 0.0},
                   'diff': {'O3': 0.0,
                            'O2': -1.730862900828356e-05,
                            'CH3COOH': 0.0,
                            'CH2O': 0.0,
                            'N2O2': 0.0,
                            'NO': 0.0,
                            'N2O4': 0.0,
                            'NO2': 0.0,
                            'HCOOH': 0.0,
                            'CH3CHO': 0.0,
                            'H2CO3': 0.0,
                            'N2': 0.0,
                            'NO3': 0.0,
                            'N2O': 0.0,
                            'CH4': 0.0,
                            'CH3OH': 0.0,
                            'CO2': 0.0,
                            'C2H5OH': 0.0,
                            'H2O': -3.461725801656712e-05,
                            'C2H6O2': 0.0,
                            'CO': 0.0,
                            'C6H6': 0.0,
                            'HCN': 0.0,
                            'H2O2': 3.46172580165353e-05,
                            'HNO2': 0.0,
                            'SO2': 0.0,
                            'SO3': 0.0,
                            'H2S': 0.0,
                            'H2SO4': 0.0,
                            'H2': 0.0,
                            'NH3': 0.0,
                            'C4H9NH2': 0.0,
                            'C3H7NH2': 0.0,
                            'COS': 0.0,
                            'S8': 0.0,
                            'HNO3': 0.0,
                            'CH3NH2': 0.0,
                            'H2SO3': 0.0,
                            'C2H5NH2': 0.0,
                            'NOHSO4': 0.0,
                            'CS2': 0.0,
                            'CH3_C6H5': 0.0,
                            'CH3_CO_CH3': 0.0},
                   'sem': {'O3': 0.0,
                           'O2': 0.0,
                           'CH3COOH': 0.0,
                           'CH2O': 0.0,
                           'N2O2': 0.0,
                           'NO': 0.0,
                           'N2O4': 0.0,
                           'NO2': 0.0,
                           'HCOOH': 0.0,
                           'CH3CHO': 0.0,
                           'H2CO3': 0.0,
                           'N2': 0.0,
                           'NO3': 0.0,
                           'N2O': 0.0,
                           'CH4': 0.0,
                           'CH3OH': 0.0,
                           'CO2': 0.0,
                           'C2H5OH': 0.0,
                           'H2O': 0.0,
                           'C2H6O2': 0.0,
                           'CO': 0.0,
                           'C6H6': 0.0,
                           'HCN': 0.0,
                           'H2O2': 0.0,
                           'HNO2': 0.0,
                           'SO2': 0.0,
                           'SO3': 0.0,
                           'H2S': 0.0,
                           'H2SO4': 0.0,
                           'H2': 0.0,
                           'NH3': 0.0,
                           'C4H9NH2': 0.0,
                           'C3H7NH2': 0.0,
                           'COS': 0.0,
                           'S8': 0.0,
                           'HNO3': 0.0,
                           'CH3NH2': 0.0,
                           'H2SO3': 0.0,
                           'C2H5NH2': 0.0,
                           'NOHSO4': 0.0,
                           'CS2': 0.0,
                           'CH3_C6H5': 0.0,
                           'CH3_CO_CH3': 0.0},
                   'std': {'O3': 0.0,
                           'O2': 0.0,
                           'CH3COOH': 0.0,
                           'CH2O': 0.0,
                           'N2O2': 0.0,
                           'NO': 0.0,
                           'N2O4': 0.0,
                           'NO2': 0.0,
                           'HCOOH': 0.0,
                           'CH3CHO': 0.0,
                           'H2CO3': 0.0,
                           'N2': 0.0,
                           'NO3': 0.0,
                           'N2O': 0.0,
                           'CH4': 0.0,
                           'CH3OH': 0.0,
                           'CO2': 0.0,
                           'C2H5OH': 0.0,
                           'H2O': 0.0,
                           'C2H6O2': 0.0,
                           'CO': 0.0,
                           'C6H6': 0.0,
                           'HCN': 0.0,
                           'H2O2': 0.0,
                           'HNO2': 0.0,
                           'SO2': 0.0,
                           'SO3': 0.0,
                           'H2S': 0.0,
                           'H2SO4': 0.0,
                           'H2': 0.0,
                           'NH3': 0.0,
                           'C4H9NH2': 0.0,
                           'C3H7NH2': 0.0,
                           'COS': 0.0,
                           'S8': 0.0,
                           'HNO3': 0.0,
                           'CH3NH2': 0.0,
                           'H2SO3': 0.0,
                           'C2H5NH2': 0.0,
                           'NOHSO4': 0.0,
                           'CS2': 0.0,
                           'CH3_C6H5': 0.0,
                           'CH3_CO_CH3': 0.0},
                   'var': {'O3': 0.0,
                           'O2': 0.0,
                           'CH3COOH': 0.0,
                           'CH2O': 0.0,
                           'N2O2': 0.0,
                           'NO': 0.0,
                           'N2O4': 0.0,
                           'NO2': 0.0,
                           'HCOOH': 0.0,
                           'CH3CHO': 0.0,
                           'H2CO3': 0.0,
                           'N2': 0.0,
                           'NO3': 0.0,
                           'N2O': 0.0,
                           'CH4': 0.0,
                           'CH3OH': 0.0,
                           'CO2': 0.0,
                           'C2H5OH': 0.0,
                           'H2O': 0.0,
                           'C2H6O2': 0.0,
                           'CO': 0.0,
                           'C6H6': 0.0,
                           'HCN': 0.0,
                           'H2O2': 0.0,
                           'HNO2': 0.0,
                           'SO2': 0.0,
                           'SO3': 0.0,
                           'H2S': 0.0,
                           'H2SO4': 0.0,
                           'H2': 0.0,
                           'NH3': 0.0,
                           'C4H9NH2': 0.0,
                           'C3H7NH2': 0.0,
                           'COS': 0.0,
                           'S8': 0.0,
                           'HNO3': 0.0,
                           'CH3NH2': 0.0,
                           'H2SO3': 0.0,
                           'C2H5NH2': 0.0,
                           'NOHSO4': 0.0,
                           'CS2': 0.0,
                           'CH3_C6H5': 0.0,
                           'CH3_CO_CH3': 0.0}}


def test_count_path_length():
    outputdata = loadfn("./test_arcs_output.json")
    analysis = AnalyseSampling()
    assert analysis.count_path_length(outputdata) == {3: 1}


def test_result_to_pyvis():
    outputdata = loadfn("./test_arcs_output.json")
    pvg = AnalyseSampling().result_to_pyvis(outputdata)
    assert pvg.__str__() == '{\n    "Nodes": [\n        "H2O2",\n        "0",\n        "H2O",\n        "O2"\n    ],\n    "Edges": [\n        {\n            "width": 1,\n            "from": "H2O2",\n            "to": "0"\n        },\n        {\n            "width": 1,\n            "from": "0",\n            "to": "H2O"\n        },\n        {\n            "width": 1,\n            "from": "0",\n            "to": "O2"\n        }\n    ],\n    "Height": "600px",\n    "Width": "100%",\n    "Heading": ""\n}'
